title: Eitamar Saraf # your name (or website title) here
logo: "/images/myself.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Eitamar Saraf, and I'm a data scientist with four years of experience in computer vision, 
  NLP, and full-stack engineering. 
  I hold a B.Sc. in computer science and mathematics from Ariel University and an 
  M.Sc. in computer science from Bar Ilan University, where I completed my thesis under the supervision of 
  Prof. <a href="https://nshomron.github.io/">Prof. Noam Shomron</a> and 
  Prof. <a href="https://yolo.math.biu.ac.il/">Prof. Yoram Louzoun</a>
  on the subject of deep learning-based DNA separation. 
  In my professional experience, I have developed ML and DL models for applications in computer vision 
  and NLP, built full-stack web applications, 
  and led projects from concept to completion. 
  Outside work, I'm an amateur farmer, an avid reader,
  and an occasional tinkerer who enjoys repairing and building computers.
  <br><br>
  <a href="https://drive.google.com/file/d/1_HSRdkK_51YfzJseJX5JKf5zGuFOrDBI/view?usp=share_link">View My CV</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/eitamar-saraf-490a3687/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R6QJBM3FHD # your Google Analytics tracking ID here
