title: Eitamar Saraf # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Enthusiastic Data Scientist with experiance developing ML/DL models.
  Working with visual and temopral data. 
  Personal experience with NLP and speech.
  <br><br>  
  Previously held a number of roles as a full-stack team leader, as well as a product manager and project manager.
  Currently pursuing my master's degree at Bar Ilan University under the supervision of <a href="https://nshomron.github.io/">Professor Noam Shomron.</a> 
  <br><br>
  <a href="https://drive.google.com/file/d/1EzgJcJf4jtREqYAvMqt5wPPZEIWr4RkG/view?usp=sharing">View My CV</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/eitamar-saraf-490a3687/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R6QJBM3FHD # your Google Analytics tracking ID here
