title: Eitamar Saraf # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Enthusiastic Data Scientist with experiance developing ML/DL models.
  Working with visual and temopral data. 
  Some personal experiance with NLP and speech.
  <br><br>
  Previously held a number of roles.
  As a full-stack team leader. As a product manager and project manager.
  Currently nearing the end of my master's degree at Bar Ilan University under the supervision of Professor Noam Shomron.
  <br><br>
  <a href="https://www.linkedin.com/in/eitamar-saraf-490a3687/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R6QJBM3FHD # your Google Analytics tracking ID here
