title: Eitamar Saraf # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A data scientist with more than
  three years of experience in
  computer vision and natural
  language processing, I am
  looking for a research position
  involving the development of
  machine and deep learning
  models for computer vision or
  natural language processing.
  Aside from my professional life,
  I am an amateur farmer and a
  DevOps enthusiast, and I have
  been repairing and building
  computers since I was 13 years
  old. 
  <br><br>
  <a href="https://drive.google.com/file/d/1_HSRdkK_51YfzJseJX5JKf5zGuFOrDBI/view?usp=share_link">View My CV</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/eitamar-saraf-490a3687/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R6QJBM3FHD # your Google Analytics tracking ID here
