title: Eitamar Saraf # your name (or website title) here
logo: "/images/myself.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With over three years of experience in computer vision and natural language processing, 
  I like good software engineering and DevOps as side projects. 
  I completed my B.Sc. in computer science and mathematics at Ariel University and my M.Sc. 
  in computer science at Bar Ilan University under (Prof. Noam Shomron)[https://nshomron.github.io/] and (Prof. Yoram Louzoun)[https://yolo.math.biu.ac.il/]. 
  In addition to my professional life, I'm an amateur farmer and a voracious reader, 
  and I've been repairing and building computers since I was 13.
  <br><br>
  <a href="https://drive.google.com/file/d/1_HSRdkK_51YfzJseJX5JKf5zGuFOrDBI/view?usp=share_link">View My CV</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/eitamar-saraf-490a3687/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-R6QJBM3FHD # your Google Analytics tracking ID here
